---
################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    # SampleSingleMSPSolo defines a configuration which contains a single MSP
    # definition (the MSP sampleconfig).
    FourOrgs:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *peerOrg0
                - *peerOrg1
                - *peerOrg2
                - *peerOrg3

################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererOrg

        # ID to load the MSP definition as
        ID: OrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: chaincode_sample/crypto/orderer/localMspConfig

    - &peerOrg0
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org0

        # ID to load the MSP definition as
        ID: Org0MSP

        # MSPDir is the filesystem path which contains the MSP configuration
        #MSPDir: /opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode_sample/crypto/peer/peer0/localMspConfig
        MSPDir: chaincode_sample/crypto/peer/peer0/localMspConfig
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: 172.19.0.3
              Port: 7051

    - &peerOrg1
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org1

        # ID to load the MSP definition as
        ID: Org1MSP

        # MSPDir is the filesystem path which contains the MSP configuration
        #MSPDir: /opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode_sample/crypto/peer/peer1/localMspConfig
        MSPDir: chaincode_sample/crypto/peer/peer1/localMspConfig
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: 172.19.0.4
              Port: 7051

    - &peerOrg2
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org2

        # ID to load the MSP definition as
        ID: Org2MSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: chaincode_sample/crypto/peer/peer2/localMspConfig
        #MSPDir: /opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode_sample/crypto/peer/peer2/localMspConfig
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: 172.19.0.5
              Port: 7051

    - &peerOrg3
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org3

        # ID to load the MSP definition as
        ID: Org3MSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: chaincode_sample/crypto/peer/peer3/localMspConfig
        #MSPDir: /opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode_sample/crypto/peer/peer3/localMspConfig
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: 172.19.0.6
              Port: 7051


################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - 127.0.0.1:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 10s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:
