version: '2'
networks:
   bridge:

services:

#TODO: Disable till SDK is ready to consume
#  ca:
#    image: hyperledger/fabric-ca
#    ports:
#      - 7054:7054
#    environment:
#      - CA_CERTIFICATE=peerOrg0_cert.pem
#      - CA_KEY_CERTIFICATE=peerOrg0_pk.pem
#    volumes:
#        - ./tmp/ca:/.fabric-ca
#    command: sh -c 'sleep 10; fabric-ca server start -ca /.fabric-ca/$$CA_CERTIFICATE -ca-key /.fabric-ca/$$CA_KEY_CERTIFICATE -config /etc/hyperledger/fabric-ca/server-config.json -address "0.0.0.0"'
#    container_name: ca

  orderer:
    container_name: orderer
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/localMspConfig
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./crypto/orderer:/var/hyperledger/orderer
    ports:
      - 7050:7050
    networks:
      - bridge
  
  peer0:
    container_name: peer0
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp/peer0/localMspConfig
      - CORE_PEER_LOCALMSPID=Org0MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto/peer/:/var/hyperledger/msp/
        - ./examples/:/opt/gopath/src/github.com/hyperledger/fabric/examples/
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer
    networks:
      - bridge

  peer1:
    container_name: peer1
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0:7051
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp/peer1/localMspConfig
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto/peer/:/var/hyperledger/msp/
        - ./examples/:/opt/gopath/src/github.com/hyperledger/fabric/examples/
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
      - orderer
      - peer0
    networks:
      - bridge

  peer2:
    container_name: peer2
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0:7051
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp/peer2/localMspConfig
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto/peer/:/var/hyperledger/msp/
        - ./examples/:/opt/gopath/src/github.com/hyperledger/fabric/examples/
    ports:
      - 9051:7051
      - 9053:7053
    depends_on:
      - orderer
      - peer0
      - peer1
    networks:
      - bridge

  peer3:
    container_name: peer3
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer3
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0:7051
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp/peer3/localMspConfig
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto/peer/:/var/hyperledger/msp/
        - ./examples/:/opt/gopath/src/github.com/hyperledger/fabric/examples/
    ports:
      - 10051:7051
      - 10053:7053
    depends_on:
      - orderer
      - peer0
      - peer1
      - peer2
    networks:
      - bridge

  cli:
    container_name: cli
    image: hyperledger/fabric-peer
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_NEXT=true
      - CORE_PEER_ID=cli
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
      - CORE_PEER_ADDRESS=peer0:7051
      - CORE_PEER_GOSSIP_IGNORESECURITY=true
      - CORE_PEER_LOCALMSPID=Org0MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/msp/sampleconfig
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: sh -c './script.sh; sleep 100000'
    #command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./examples/:/opt/gopath/src/github.com/hyperledger/fabric/examples/
        - ./crypto/orderer/channel.tx:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel.tx
        - ./crypto/peer/peer0/localMspConfig:/opt/gopath/src/github.com/hyperledger/fabric/msp/sampleconfig
        - ./crypto:/opt/gopath/src/github.com/hyperledger/fabric/chaincode_sample/crypto/
        - ./single_channel.sh:/opt/gopath/src/github.com/hyperledger/fabric/peer/script.sh
    depends_on:
      - orderer
      - peer0
      - peer1
      - peer2
    networks:
      - bridge
